import LoginForm from '../components/loginForm/login-form'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/header'

import styles from '../styles/Home.module.css'
import Logo from '../components/logo/Logo'

export default function Login() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Dunya: Login</title>

          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/plane.ico" />
        </Head>
        {/* <Header/> */}
        <Logo/>
        <main>
          <LoginForm/>
        </main>
    </div>
    
    );
  }